#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

DOMAIN="akshayprabhakant.com"
D1_NAME="ai-chat-archive"
WRANGLER_CONFIG="backend/wrangler.jsonc"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# ── helpers local to these stages ─────────────────────────────────────────

# wrangler needs an npm cache it can write to. On a machine where a previous
# npm wrote root-owned files there, every npx call dies with EPERM before it
# reaches Cloudflare. Only redirect when the default is actually unusable, so
# this is a no-op on a healthy machine.
if [[ ! -w "${npm_config_cache:-$HOME/.npm}" ]]; then
  export npm_config_cache="${TMPDIR:-/tmp%/}/npm-cache"
  note "npm cache redirected to $npm_config_cache (default not writable)"
fi

_have() { command -v "$1" >/dev/null 2>&1; }

# _json FILE EXPR — read a value out of JSON on stdin. python3 over jq because
# python3 is already a hard requirement of this repo and jq is not.
_json() { python3 -c "import json,sys;d=json.load(sys.stdin);print($1)" 2>/dev/null || true; }

# cf_api PATH — GET a Cloudflare API path with the token captured so far.
# Prints the body; returns non-zero when the API says the call failed.
cf_api() {
  local path="$1" body
  body=$(curl -sS -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
    "https://api.cloudflare.com/client/v4${path}" 2>/dev/null) || return 1
  printf '%s' "$body" | grep -q '"success": *true' || return 1
  printf '%s' "$body"
}

# wrun ... — run wrangler from backend/ with this run's credentials, and
# without wrangler prodding an interactive login.
wrun() {
  ( cd backend && CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" \
      CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" \
      npx --yes wrangler "$@" )
}

# set_d1_id UUID — write the database id into wrangler.jsonc in place.
set_d1_id() {
  python3 - "$1" <<'PY'
import re, sys, pathlib
new_id = sys.argv[1]
p = pathlib.Path("backend/wrangler.jsonc")
s = p.read_text()
s2, n = re.subn(r'("database_id"\s*:\s*)"[^"]*"', lambda m: m.group(1) + '"' + new_id + '"', s, count=1)
if n != 1:
    sys.exit("could not find database_id in wrangler.jsonc")
p.write_text(s2)
PY
  printf '  %s✓ wrote%s database_id → %s\n' "$GREEN" "$RESET" "$WRANGLER_CONFIG"
}

# ── stages ────────────────────────────────────────────────────────────────

banner "Deploy the AI Chat Archive to Cloudflare"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The zone exists on Cloudflare"
say "Everything below hangs off $DOMAIN being an active zone in your account."
open_url "https://dash.cloudflare.com/"
step "Select the $DOMAIN zone."
step "Check the Overview panel says the zone is Active."
step "Then DNS → Records: the apex should have a proxied (orange cloud) record."
note "If the zone is not here, add the site and change the nameservers at your"
note "registrar first. Routes attach to a zone, so nothing else can work until"
note "this one does."
if ! confirm "Is $DOMAIN an active zone in your account?"; then
  warn "Stop here and get the zone active, then re-run this wizard."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "API token — with D1 added by hand"
say "The Edit Cloudflare Workers template does NOT include D1. That omission is"
say "the whole reason this stage exists: without it a deploy succeeds and the"
say "migration silently cannot run."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → 'Edit Cloudflare Workers' → Use template."
step "Account Resources: include your account."
step "Zone Resources: include $DOMAIN."
step "Still in Permissions, press '+ Add more' and add:  Account · D1 · Edit"
step "Continue to summary → Create Token → copy it."
ask_secret CLOUDFLARE_API_TOKEN "Paste the token:"

if [[ -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  warn "No token given, so there is nothing to verify. Re-run when you have one."
  exit 1
fi

say ""
say "Checking the token actually carries D1, rather than assuming it..."
if ! accounts=$(cf_api "/accounts"); then
  warn "The Cloudflare API rejected this token outright."
  note "Usually a bad paste, or the token was created for a different account."
  exit 1
fi
printf '  %s✓%s token is valid\n' "$GREEN" "$RESET"

# The account id is right there in the response, so do not make anyone copy it.
CLOUDFLARE_ACCOUNT_ID=$(printf '%s' "$accounts" | _json 'd["result"][0]["id"]')
N_ACCOUNTS=$(printf '%s' "$accounts" | _json 'len(d["result"])')
if [[ "$N_ACCOUNTS" != "1" ]]; then
  warn "This token can see $N_ACCOUNTS accounts; we assume the first."
  printf '%s' "$accounts" | python3 -c '
import json, sys
for a in json.load(sys.stdin)["result"]:
    print("    -", a["id"], a["name"])
' || true
  note "If that is wrong, edit CLOUDFLARE_ACCOUNT_ID in .env and re-run."
fi
say "  account id: $CLOUDFLARE_ACCOUNT_ID   (read off the token, not typed)"

if cf_api "/accounts/${CLOUDFLARE_ACCOUNT_ID}/d1/database" >/dev/null; then
  printf '  %s✓%s token can reach D1\n' "$GREEN" "$RESET"
else
  warn "This token CANNOT reach D1 — the exact problem this stage guards against."
  note "Go back to the token's Permissions and add:  Account · D1 · Edit"
  note "Editing a token's permissions does not always reissue it; if in doubt,"
  note "create a fresh token and paste that."
  exit 1
fi

set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
# The account id is not a credential, so it is also kept locally where the
# wrangler commands below can pick it up. The token deliberately is not: it
# belongs in CI, and a second copy on disk is a liability with no upside.
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the D1 database"
existing=$(grep -oE '"database_id"\s*:\s*"[^"]*"' "$WRANGLER_CONFIG" | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
if [[ "$existing" != "REPLACE_WITH_YOUR_D1_DATABASE_ID" && -n "$existing" ]]; then
  say "$WRANGLER_CONFIG already names a database:"
  note "  $existing"
  if confirm "Keep it and skip creation?"; then
    note "keeping the existing database id"
  else
    existing=""
  fi
fi

if [[ "${existing:-}" == "REPLACE_WITH_YOUR_D1_DATABASE_ID" || -z "${existing:-}" ]]; then
  say "Creating '$D1_NAME' with a location hint of apac."
  note "A hint, not a promise: it does not guarantee the database runs there."
  note "A jurisdiction (eu/us/fedramp) would be permanent and set only at"
  note "creation — this project stores nothing that requires one."
  if ! out=$(wrun d1 create "$D1_NAME" --location apac 2>&1); then
    warn "d1 create failed:"
    printf '%s\n' "$out" | sed 's/^/    /'
    note "If it mentions authentication, the token is missing D1 Edit (stage 2)."
    exit 1
  fi
  printf '%s\n' "$out" | grep -E 'database_id|"uuid"' | sed 's/^/    /' || true
  D1_ID=$(printf '%s' "$out" | grep -oE '"database_id"\s*:\s*"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')
  if [[ -z "${D1_ID:-}" ]]; then
    D1_ID=$(wrun d1 list --json 2>/dev/null | python3 -c \
      "import json,sys;print(next((d['uuid'] for d in json.load(sys.stdin) if d.get('name')=='$D1_NAME'),''))" 2>/dev/null || true)
  fi
  if [[ -z "${D1_ID:-}" ]]; then
    D1_ID=$(wrun d1 list 2>/dev/null | grep -E "\b$D1_NAME\b" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)
  fi
  [[ -n "${D1_ID:-}" ]] || { warn "Created, but could not read the id back. Copy it into $WRANGLER_CONFIG by hand."; exit 1; }
  set_d1_id "$D1_ID"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Apply the schema"
say "Migrations, not a bare schema file: the runner records what it applied in"
say "a d1_migrations table, backs up first, and rolls a failed one back."
say ""
say "Local first, so a broken migration is found before it touches production."
if ! out=$(wrun d1 migrations apply "$D1_NAME" --local 2>&1); then
  warn "Local migration failed:"; printf '%s\n' "$out" | sed 's/^/    /'; exit 1
fi
printf '%s\n' "$out" | tail -5 | sed 's/^/    /'
printf '  %s✓%s local database migrated\n' "$GREEN" "$RESET"

if confirm "Apply the same migrations to the REMOTE database?"; then
  if ! out=$(wrun d1 migrations apply "$D1_NAME" --remote 2>&1); then
    warn "Remote migration failed:"; printf '%s\n' "$out" | sed 's/^/    /'; exit 1
  fi
  printf '%s\n' "$out" | tail -5 | sed 's/^/    /'
  printf '  %s✓%s remote database migrated\n' "$GREEN" "$RESET"
else
  warn "Skipped — the Worker will deploy against an empty database."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Deploy the API Worker"
say "Python Workers deploy through pywrangler, which wraps wrangler."
_have uv || { warn "uv is not installed, and pywrangler needs it."; note "Install: curl -LsSf https://astral.sh/uv/install.sh | sh"; exit 1; }

# Sync first, so the virtualenv matches pyproject before anything is spawned.
#
# This is the step that installs pywrangler, which arrives as the `workers-py`
# dev dependency. Going straight to `uv run pywrangler deploy` is how the first
# run of this wizard failed: a bare "Failed to spawn: `pywrangler`" that says
# nothing about the cause and sends you looking at Cloudflare instead of at a
# missing line in pyproject.toml.
say "Syncing the Python environment (this is what installs pywrangler)..."
if ! out=$(cd backend && uv sync 2>&1); then
  warn "uv sync failed:"; printf '%s\n' "$out" | tail -15 | sed 's/^/    /'; exit 1
fi
if ! (cd backend && uv run pywrangler --version >/dev/null 2>&1); then
  warn "uv sync succeeded but pywrangler still does not resolve."
  note "Check that 'workers-py' is in the dev dependency group in"
  note "backend/pyproject.toml — it is what provides the pywrangler command."
  exit 1
fi
printf '  %s✓%s pywrangler is installed\n' "$GREEN" "$RESET"

if confirm "Run 'uv run pywrangler deploy' now?"; then
  if ! out=$(cd backend && CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN" \
      CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID" uv run pywrangler deploy 2>&1); then
    warn "Deploy failed:"; printf '%s\n' "$out" | tail -25 | sed 's/^/    /'
    if printf '%s' "$out" | grep -q 'Failed to spawn'; then
      note "That is a missing tool, not a problem with Cloudflare."
      note "Run 'cd backend && uv sync' and try again."
    else
      note "Routes attach to a zone, so a zone or DNS problem surfaces here."
    fi
    exit 1
  fi

  printf '%s\n' "$out" | tail -12 | sed 's/^/    /'
  printf '  %s✓%s deployed\n' "$GREEN" "$RESET"
else
  warn "Skipped the deploy; the verification stages below will fail."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify the Worker answers — and that Access reached it"
say "GET /api/health is a public endpoint that reports whether Python Workers"
say "actually expose self.ctx. ctx.access is documented for JavaScript only, so"
say "this is how the deployed Worker answers the question instead of us assuming."
say ""
HEALTH_URL="https://${DOMAIN}/api/health"
for attempt in 1 2 3 4 5; do
  body=$(curl -sS --max-time 20 "$HEALTH_URL" 2>/dev/null || true)
  if [[ -n "$body" ]]; then break; fi
  note "no response yet (attempt $attempt/5) — routes can take a moment to settle"
  sleep 5
done
if [[ -z "$body" ]]; then
  warn "$HEALTH_URL did not answer."
  note "Check the route pattern in $WRANGLER_CONFIG and that DNS is proxied."
  exit 1
fi
printf '%s\n' "$body" | sed 's/^/    /'
if printf '%s' "$body" | grep -q '"context_available": *true'; then
  printf '  %s✓%s self.ctx exists — the identity wiring can work\n' "$GREEN" "$RESET"
else
  warn "context_available is not true."
  note "If you chose Cloudflare Access to own the login, every protected route"
  note "will now 401 — fail-closed, but with no way in. docs/access-limits.md"
  note "has the two options; read it before going further."
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "File one session, end to end"
say "A deployment nobody has used once is not a deployment."
open_url "https://${DOMAIN}/chat-archives/desk"
step "Sign in, then paste a ChatGPT share link and file it."
step "Open the story — the report should render, and the transcript should show"
step "its sources behind the ··· on the assistant's turn."
open_url "https://${DOMAIN}/chat-archives"
step "Confirm the story is on the front page, readable signed out."
if confirm "Did the session file and read back correctly?"; then
  printf '  %s✓%s end to end\n' "$GREEN" "$RESET"
else
  warn "Worth fixing before wiring CI: a pipeline that deploys a broken Worker"
  warn "faster is not an improvement."
fi

finish
